---
os: linux
dist: bionic
language: ruby
cache: bundler

services:
  - mysql
  - postgresql

rvm:
  - 2.7
  - 2.6

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_6.0.gemfile

bundler_args: '--without local_development --jobs 3 --retry 3'

before_install:
  - gem install bundler

script: bundle exec rake

jobs:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
