---
name: MySQL CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  mysql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MSQL_DATABASE: my_sql_test_db
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        env:
          DATABASE_URL: mysql2://root:password@127.0.0.1:3306/my_sql_test_db
          RAILS_ENV: test
        run: |
          gem update --system
          bundle exec appraisal install
          bundle exec rake test_app
          bundle exec appraisal rake
