---
name: Postgres CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pg_test
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gem-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec appraisal install

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/pg_test
          RAILS_ENV: test
        run: |
          bundle exec appraisal rake
