---
name: Postgres CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pg_test
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/pg_test
          RAILS_ENV: test
        run: |
          gem update --system
          bundle exec appraisal install
          bundle exec rake test_app
          bundle exec appraisal rake
