---
name: SQLite CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          gem update --system
          bundle exec appraisal install
          bundle exec rake test_app
          bundle exec appraisal rake
