---
name: Standard Rb

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  # STANDARD RB
  standard:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Standard Rb
        run: bundle exec standardrb --format progress
